board:
  dark_tile: !!python/tuple
  - 101
  - 67
  - 33
  light_tile: !!python/tuple
  - 181
  - 101
  - 29
  outline_color: !!python/tuple
  - 0
  - 0
  - 0
  outline_width: 2
  rank_and_file_font_color: !!python/tuple
  - 255
  - 179
  - 71
  rank_and_file_font_size: 16
depth:
  color_palette:
  - !!python/tuple
    - 164
    - 198
    - 57
  - !!python/tuple
    - 255
    - 191
    - 0
  - !!python/tuple
    - 153
    - 102
    - 204
  - !!python/tuple
    - 251
    - 96
    - 127
  - !!python/tuple
    - 102
    - 153
    - 204
  - !!python/tuple
    - 18
    - 97
    - 128
  - !!python/tuple
    - 255
    - 0
    - 0
stats:
  black_font_color: !!python/tuple
  - 102
  - 102
  - 153
  font_color: !!python/tuple
  - 253
  - 253
  - 150
  font_size: 12
  white_font_color: !!python/tuple
  - 196
  - 195
  - 208
